### ISSUE TITLE
G - ani muž ani žena

### ISSUE THREAD

**Issue by EvaMach** [KristynaSodomkova/forcheck#2]
Tady je problém s tím, co neguješ. 😊 
`console.log(persons.some((ppl) => !ppl.gender === "male" && !ppl.gender === "female"));` říká, že NE property ppl.gender, která má hodnotu 'male' a zároveň NE property ppl.gender, která má hodnotu 'female'. My ale chceme property ppl.gender, která NEMÁ nějakou hodnotu. Takže přesunout vykřičníky a mělo by to fungovat. 😊

**Comment by KristynaSodomkova** [comment]
Super, opraveno v hlavním repozitáři, děkuju!
console.log(persons.some((ppl) => ppl.gender !== "male" && ppl.gender !== "female"));
